# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DataTeaser - Software Research and Development
email: jolo@datateaser.com
description: > # this means to ignore newlines until "baseurl:"
  DataTeaser is a software research and development company. We have a good understanding in machine learning, natural language processing, and data science.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://www.datateaser.com/" # the base hostname & protocol for your site
twitter_username: DataTeaser_
github_username:  DataTeaser

# Build settings
markdown: kramdown
